; Script generated by the HM NIS Edit Script Wizard.
InstallDir "$PROGRAMFILES\RetronBMS"
OutFile "app.exe"
Name "Retron BMS"
RequestExecutionLevel user

Section
SetOutPath "$INSTDIR"
File "D:\Vinay-Work\TestS\bms-ver1-production\dist\app\app.exe"
; Include any additional files your app needs
; File "path\to\your\additional\file"
SectionEnd
